config/routes.rb
# 
Rails.application.routes.draw do
  root 'home#index'
  resources :articales

  get 'signup', to: 'users#new'
  resources :users

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :categories, except: [:destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/articale.rb
# == Schema Information
#
# Table name: articales
#
#  id          :integer          not null, primary key
#  description :text
#  title       :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  user_id     :integer
#

class Articale < ApplicationRecord
  has_many :articale_categories
  has_many :categories, through: :articale_categories
  belongs_to :user
  validates :title, presence: true, length: {minimum: 4, maximum: 100}
  validates :description, presence: true, length: {minimum: 5, maximum: 300}
end

app/models/articale_category.rb
# == Schema Information
#
# Table name: articale_categories
#
#  id          :integer          not null, primary key
#  articale_id :integer
#  category_id :integer
#
class ArticaleCategory < ApplicationRecord
  belongs_to :articale
  belongs_to :category
end

app/models/category.rb
# == Schema Information
#
# Table name: categories
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Category < ApplicationRecord
  validates :name, presence: true, length: {minimum: 5, maximum: 30}
  validates_uniqueness_of :name
  has_many :articale_categories
  has_many :articales, through: :articale_categories
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  admin           :boolean          default(FALSE)
#  email           :string
#  password_digest :string
#  username        :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#
class User < ApplicationRecord
  before_save {self.email = email.downcase}
  has_many :articales, dependent: :destroy
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true,
                    uniqueness: {case_sensitive: false},
                    length: {maximum: 100},
                    format: { with: VALID_EMAIL_REGEX }
  validates :username, presence: true, uniqueness: {case_sensitive: false}, length: {minimum: 3, maximum: 15}
  has_secure_password
  validates :password, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end
  
  def require_user
    if !logged_in?
      flash[:alert] = "You must be logged in to perform that action"
      redirect_to login_path
    end
  end
end

app/controllers/articales_controller.rb
# Aricale Controller
class ArticalesController < ApplicationController
  before_action :set_articale, only: [:edit, :update, :show, :destroy]
  before_action :require_user, except: [:show, :index]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def index
    @articales = Articale.paginate(page: params[:page], per_page: 5)
  end

  def show
  end

  def new
    @articale = Articale.new
  end

  def create
    @articale = Articale.new(params.require(:articale).permit(:title, :description, category_ids: []))
    @articale.user = current_user
    if @articale.save
      flash[:notice] = 'Article was created successfully.'
      redirect_to articale_path(@articale) 
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @articale.update(params.require(:articale).permit(:title, :description, category_ids: []))
      flash[:notice] = 'Article was updated successfully.'
      redirect_to articale_path(@articale)
    else
      render 'edit'
    end
  end

  def destroy
    @articale.destroy
    flash[:notice] = 'Article was deleted successfully.'
    redirect_to articales_path
  end

  private

  def set_articale
    @articale = Articale.find(params[:id])
  end

  def require_same_user
    if current_user != @articale.user && !current_user.admin?
      flash[:alert] = "You can only edit or delete your own article"
      redirect_to @articale
    end
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_admin, except: [:index, :show]
  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = 'Category was successfully created'
      redirect_to @category
    else
      render 'new'
    end
  end

  def index
    @categories = Category.paginate(page: params[:page], per_page: 5)
  end

  def show
    @category = Category.find(params[:id])
    @articales = @category.articales.paginate(page: params[:page], per_page: 5)
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      flash[:notice] = "Category name updated successfully"
      redirect_to @category
    else
      render 'edit'
    end
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end

  def require_admin
    if !(logged_in? && current_user.admin?)
      flash[:alert] = 'Only admins can perform that action'
      redirect_to categories_path
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    redirect_to user_path(current_user) if current_user
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:notice] = 'Logged in successfully'
      redirect_to user
    else
      flash.now[:alert] = 'There was something wrong with your login details'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "Logged out"
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_user, only: [:edit, :update]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def show
    @articales = @user.articales.paginate(page: params[:page], per_page: 5)
  end

  def new
    redirect_to user_path(current_user) if current_user
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Welcome to the Alpha Blog #{@user.username}, you have successfully signed up"
      redirect_to articales_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:notice] = 'Your account information was successfully updated'
      redirect_to @user
    else
      render 'edit'
    end
  end

  def index
    @users = User.paginate(page: params[:page], per_page: 5)
  end

  def destroy
    @user.destroy
    session[:user_id] = nil if @user == current_user
    flash[:notice] = "Account and all associated articles successfully deleted"
    redirect_to articales_path
  end

  private
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def require_same_user
    if current_user != @user && !current_user.admin?
      flash[:alert] = "You can only edit or delete your own account"
      redirect_to @user
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, options = { size: 80})
    email_address = user.email.downcase
    hash = Digest::MD5.hexdigest(email_address)
    size = options[:size]
    gravatar_url = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: "rounded shadow mx-auto d-block")
  end

end

app/views/articales/_article.html.erb
    <div class="container">
        <% @articales.each do |articale| %>
            <div class="row justify-content-md-center">
            <div class="col-8 mt-4">
                <div class="card text-center shadow mb-5 bg-white rounded">
                <div class="card-header font-italic">
                    <% if articale.user %>
                      by <%= link_to articale.user.username, user_path(articale.user) %>
                    <% end %>
                      <% if articale.categories.any? %>
                        <div class="mt-2"><%= render articale.categories %></div> 
                      <% end %>
                </div>
                <div class="card-body">
                    <h5 class="card-title"><%= link_to articale.title, articale_path(articale), class: "text-success" %></h5>
                    <p class="card-text"><%= truncate(articale.description, length: 100) %></p>
                    <div class="row">
                        <div class="col">
                            <%= link_to "View", articale_path(articale), class: "btn btn-outline-success" %>
                        </div>
                        <% if logged_in? && (articale.user == current_user || current_user.admin?) %>
                            <div class="col">
                                <%= link_to "Edit", edit_articale_path(articale), class: "btn btn-outline-info" %>
                            </div>
                            <div class="col">
                                <%= button_to "Delete", articale_path(articale), class: "btn btn-outline-danger", method: :delete, data: {confirm: "Are you sure?"} %>
                            </div>
                        <% end %>
                    </div>
                </div>
                <div class="card-footer text-muted">
                    <small>Created <%= time_ago_in_words(articale.created_at) %> ago, 
                    edited <%= time_ago_in_words(articale.updated_at) %> ago</small>
                </div>
                </div>
            </div>
            </div>
        <% end %>
    </div>

app/views/articales/_validation_messages.html.erb
<% if @articale.errors.any? %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <h4 class="alert-heading">The following errors prevented the article from being saved</h4>
    <ul>
      <% @articale.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %> 

app/views/articales/edit.html.erb
<h1 class="text-center mt-4">Edit article</h1>

<div class="container">
  
  <%= render "articales/validation_messages"%>

   <div class="row justify-content-center">
    <div class="col-10">
      <%= form_with(model: @articale, class: "shadow p-3 mb-3 bg-info rounded", local: true) do |f| %>
        <div class="form-group row">
          <%= f.label :title, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.text_field :title, class: "form-control shadow rounded", placeholder: "Title of article" %>
          </div>
        </div>

        <div class="form-group row mt-1">
          <%= f.label :description, class: "col-2 col-form-label text-light" %>
          <div class="col-10"> 
            <%= f.text_area :description, rows: 10, class: "form-control shadow rounded", placeholder: "Description of article" %>
          </div>
        </div>  
        
        <div class="form-group row justify-content-center mt-2">
          <%= f.submit class: "btn btn-outline-light" %>
        </div>
      <% end %>
    </div>
    <div class="row justify-content-center">
      <%= link_to '[ Cancel and return to articles listing ]', articales_path, class: "text-info" %>
    </div>
  </div>
</div>  

app/views/articales/index.html.erb
 <h1 class="text-center">Blog</h1>
<div id="page-content">
    <% if logged_in? %>
        <div class="text-center">
            <%= link_to "Create new article", new_articale_path, class: "btn btn-primary border-0" %>
        </div>
    <% end %>  
    <div class="flickr_pagination">
        <%= will_paginate @articales, :container => false %>
    </div>
    <%= render 'article' %>
    <div class="flickr_pagination mb-4">
        <%= will_paginate @articales, :container => false %>
    </div> 
</div> 

app/views/articales/show.html.erb
<div id="page-content">
  <h2 class="text-center mt-4"><%= @articale.title %></h2>

  <div class="container">
    <div class="row justify-content-center">
      <div class="col-12 col-md-8 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-header font-italic">
            by <%= @articale.user.username if @articale.user %>
            <%= link_to gravatar_for(@articale.user), user_path(@articale.user) %>  
              <% if @articale.categories.any? %>
                <div class="mt-2"><%= render @articale.categories %></div> 
              <% end %>
          </div>
          <div class="card-body">
            <div class="card-text text-left"><%= simple_format(@articale.description) %></div>
            <% if logged_in? && (@articale.user == current_user  || current_user.admin?)%>   
              <%= link_to "Edit", edit_articale_path(@articale), class: "btn btn-outline-info" %>
              <%= link_to "Delete", articale_path(@articale), class: "btn btn-outline-danger", method: :delete, data: {confirm: "Are you sure?"} %>
            <% end %>          
          </div>
          <div class="card-footer text-muted">
            <small>Created <%= time_ago_in_words(@articale.created_at) %> ago, 
            edited <%= time_ago_in_words(@articale.updated_at) %> ago</small>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="container">
    <div class="row justify-content-center">
      <div class="col-10 col-md-6">
        <%= link_to '[ Cancel and return to articles listing ]', articales_path, class: "text-info" %>
      </div>
    </div>
  </div>
</div>

app/views/categories/_category.html.erb
<%= link_to category.name, category_path(category), class: "color-black mr-1" %> 

app/views/categories/_form.html.erb
<%
=begin%>
 <%= render 'shared/_flash_messages', obj: @category %> 
<%
=end%>
<%= form_with(model: @category, class: "shadow p-3 mb-3 bg-info rounded", local: true) do |f| %>
  <div class="form-group row">
    <%= f.label :name, "Category name", class: "col-2 col-form-label text-light" %>
    <div class="col-10">
      <%= f.text_field :name, class: "form-control shadow rounded", placeholder: "Enter a name" %>
    </div>
  </div>

  <div class="form-group row justify-content-center mt-2">
    <%= f.submit class: "btn btn-outline-light btn-lg" %>
  </div>
<% end %>

app/views/categories/_validation_messages.html.erb
<% if @category.errors.any? %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <h4 class="alert-heading">The following errors prevented the category from being saved</h4>
    <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %> 

app/views/categories/edit.html.erb
<h1 class="text-center mt-4">Edit category name</h1>
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render 'form' %>
    </div>
    <div class="mb-3">
      <%= link_to '[ Cancel and return to category ]', category_path(@category), class: "text-info" %>
    </div>
  </div>
</div>

app/views/categories/index.html.erb
<h1 class="text-center mt-4">Categories</h1>

    <% if logged_in? && current_user.admin? %>
        <div class="text-center">
            <%= link_to "Create new category", new_category_path, class: "btn btn-primary border-0" %>
        </div>
    <% end %>  

<div class="flickr_pagination">
  <%= will_paginate @categories, :container => false %>
</div>

<div class="container">
  <% @categories.each do |category| %>
    <div class="row justify-content-md-center">
      <div class="col-4 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-body">
            <h5 class="card-title"><%= link_to category.name, category_path(category), class: "text-success" %></h5>
                <p class="card-text"><%= pluralize(category.articales.count, "article") %></p>
            </div>
          <div class="card-footer text-muted">
            <small>Created <%= time_ago_in_words(category.created_at) %> ago, 
            edited <%= time_ago_in_words(category.updated_at) %> ago</small>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

<div class="flickr_pagination mb-4">
  <%= will_paginate @categories, :container => false %>
</div>

app/views/categories/show.html.erb
<h1 class="text-center mt-4">Category: <%= @category.name %></h1>

<% if logged_in? && current_user.admin? %>
  <div class="text-center mt-4">
    <%= link_to "Edit category name", edit_category_path(@category), class: "btn btn-outline-info" %>
  </div>
<% end %>

<h3 class="text-center mt-4">Articles</h3>

    <div class="flickr_pagination">
        <%= will_paginate @articales, :container => false %>
    </div>
    <%= render 'articales/article' %>
    <div class="flickr_pagination mb-4">
        <%= will_paginate @articales, :container => false %>
    </div> 

app/views/home/index.html.erb
  <div id="myCarousel" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-indicators">
      <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="0" class="active" aria-label="Slide 1" aria-current="true"></button>
      <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="1" aria-label="Slide 2" class=""></button>
      <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="2" aria-label="Slide 3" class=""></button>
    </div>
    <div class="carousel-inner">
      <div class="carousel-item carousel-item-next carousel-item-start">
        <svg class="bd-placeholder-img" width="100%" height="100%" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="false"><rect width="100%" height="100%" fill="#777"></rect></svg>

        <div class="container">
          <div class="carousel-caption text-start">
            <h1>Example headline.</h1>
            <p>Some representative placeholder content for the first slide of the carousel.</p>
            <p><a class="btn btn-lg btn-primary" href="#">Sign up today</a></p>
          </div>
        </div>
      </div>
      <div class="carousel-item">
        <svg class="bd-placeholder-img" width="100%" height="100%" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="false"><rect width="100%" height="100%" fill="#777"></rect></svg>

        <div class="container">
          <div class="carousel-caption">
            <h1>Another example headline.</h1>
            <p>Some representative placeholder content for the second slide of the carousel.</p>
            <p><a class="btn btn-lg btn-primary" href="#">Learn more</a></p>
          </div>
        </div>
      </div>
      <div class="carousel-item active carousel-item-start">
        <svg class="bd-placeholder-img" width="100%" height="100%" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="false"><rect width="100%" height="100%" fill="#777"></rect></svg>

        <div class="container">
          <div class="carousel-caption text-end">
            <h1>One more for good measure.</h1>
            <p>Some representative placeholder content for the third slide of this carousel.</p>
            <p><a class="btn btn-lg btn-primary" href="#">Browse gallery</a></p>
          </div>
        </div>
      </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#myCarousel" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#myCarousel" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>


  <!-- Marketing messaging and featurettes
  ================================================== -->
  <!-- Wrap the rest of the page in another container to center all the content. -->

  <div class="container marketing mt-2">

    <!-- Three columns of text below the carousel -->
    <div class="row">
      <div class="col-lg-4">
        <svg class="bd-placeholder-img rounded-circle" width="140" height="140" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 140x140" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#777"></rect><text x="50%" y="50%" fill="#777" dy=".3em">140x140</text></svg>

        <h2>Heading</h2>
        <p>Some representative placeholder content for the three columns of text below the carousel. This is the first column.</p>
        <p>
          <%= link_to "Sign up!", signup_path, class: "btn btn-success btn-lg" %>
        </p>
      </div><!-- /.col-lg-4 -->
      <div class="col-lg-4">
        <svg class="bd-placeholder-img rounded-circle" width="140" height="140" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 140x140" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#777"></rect><text x="50%" y="50%" fill="#777" dy=".3em">140x140</text></svg>

        <h2>Heading</h2>
        <p>Another exciting bit of representative placeholder content. This time, we've moved on to the second column.</p>
        <p><a class="btn btn-secondary" href="#">View details »</a></p>
      </div><!-- /.col-lg-4 -->
      <div class="col-lg-4">
        <svg class="bd-placeholder-img rounded-circle" width="140" height="140" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 140x140" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#777"></rect><text x="50%" y="50%" fill="#777" dy=".3em">140x140</text></svg>

        <h2>Heading</h2>
        <p>And lastly this, the third column of representative placeholder content.</p>
        <p><a class="btn btn-secondary" href="#">View details »</a></p>
      </div><!-- /.col-lg-4 -->
    </div><!-- /.row -->


    <!-- START THE FEATURETTES -->

    <hr class="featurette-divider">

    <div class="row featurette">
      <div class="col-md-7">
        <h2 class="featurette-heading">First featurette heading. <span class="text-muted">It’ll blow your mind.</span></h2>
        <p class="lead">Some great placeholder content for the first featurette here. Imagine some exciting prose here.</p>
      </div>
      <div class="col-md-5">
        <svg class="bd-placeholder-img bd-placeholder-img-lg featurette-image img-fluid mx-auto" width="500" height="500" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 500x500" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#eee"></rect><text x="50%" y="50%" fill="#aaa" dy=".3em">500x500</text></svg>

      </div>
    </div>

    <hr class="featurette-divider">

    <div class="row featurette">
      <div class="col-md-7 order-md-2">
        <h2 class="featurette-heading">Oh yeah, it’s that good. <span class="text-muted">See for yourself.</span></h2>
        <p class="lead">Another featurette? Of course. More placeholder content here to give you an idea of how this layout would work with some actual real-world content in place.</p>
      </div>
      <div class="col-md-5 order-md-1">
        <svg class="bd-placeholder-img bd-placeholder-img-lg featurette-image img-fluid mx-auto" width="500" height="500" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 500x500" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#eee"></rect><text x="50%" y="50%" fill="#aaa" dy=".3em">500x500</text></svg>

      </div>
    </div>

    <hr class="featurette-divider">

    <div class="row featurette">
      <div class="col-md-7">
        <h2 class="featurette-heading">And lastly, this one. <span class="text-muted">Checkmate.</span></h2>
        <p class="lead">And yes, this is the last block of representative placeholder content. Again, not really intended to be actually read, simply here to give you a better view of what this would look like with some actual content. Your content.</p>
      </div>
      <div class="col-md-5">
        <svg class="bd-placeholder-img bd-placeholder-img-lg featurette-image img-fluid mx-auto" width="500" height="500" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 500x500" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#eee"></rect><text x="50%" y="50%" fill="#aaa" dy=".3em">500x500</text></svg>

      </div>
    </div>

    <hr class="featurette-divider">

    <!-- /END THE FEATURETTES -->

  </div><!-- /.container -->


  

app/views/shared/_flash_messages.html.erb
<div class="container mt-2">
  <% flash.each do |name, msg| %>
    <div class="alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissible fade show" role="alert">
      <%= msg %>
    </div>
  <% end %> 
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-white bg-dark fixed">
  <div class="container-fluid">
    <%= link_to "ALPHA BLOG", root_path, class: "navbar-brand", id: "logo" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "Articles", articales_path, class: "nav-link" %> 
        </li>
        <li class="nav-item">
          <%= link_to "Categories", categories_path, class: "nav-link" %> 
        </li>
        <li class="nav-item">
          <%= link_to "Bloggers", users_path, class: "nav-link" %>
        </li>
      
      </ul>
      <ul class="navbar-nav ml-auto">
          <% if logged_in? %>
          <li class="nav-item">
            <%= link_to current_user.username , user_path(current_user), class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= button_to 'Logout', logout_path, class: "nav-link btn btn-outline-danger border-0", method: :delete %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Log in', login_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Sign up', signup_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/users/index.html.erb
<h1 class="text-center mt-4">Alpha Bloggers</h1>

<div class="container">

    <div class="flickr_pagination">
    <%= will_paginate @users, :container => false %>
    </div>

  <% @users.each do |user| %>
    <div class="row justify-content-md-center">
      <div class="col-8 mt-2">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-header font-italic">
            <%= link_to user.username, user %>
          </div>
          <div class="card-body">
            <h5 class="card-title">
              <%= link_to gravatar_for(user, size: 150), user %>
            </h5>
            <p class="card-text"><%= pluralize(user.articales.count, "articale") %></p>
            <%= link_to "View profile", user, class: "btn btn-outline-success" %>
            <% if logged_in? %>
              <% if user == current_user %>
                <%= link_to "Edit profile", edit_user_path(user), class: "btn btn-outline-info" %>
              <% end %>
              <% if current_user.admin? %>
                <%= button_to "Delete user", user_path(user), class: "btn btn-outline-danger mt-2", method: :delete,
                data: {confirm: "Are you sure you want to delete the user account and all associated articles?"} %>
              <% end %>
            <% end %>
          </div>
          <div class="card-footer text-muted">
            <small>Joined <%= time_ago_in_words(user.created_at) %> ago</small>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

<div class="flickr_pagination mb-4">
  <%= will_paginate @users, :container => false %>
</div>

app/views/users/show.html.erb
<h1 class="text-center mt-4"><%= @user.username %>'s profile</h1>

<%= gravatar_for @user, size: 200 %>

<div class="mt-4">
  <% if logged_in? && @user == current_user %>
    <div class="row">
      <div class="col text-end">
        <%= link_to "Edit your profile", edit_user_path(@user), class: "btn btn-outline-info" %>
      </div>
      <div class="col text-start">
        <%= button_to "Delete your profile", user_path(@user), class: "btn btn-outline-danger", method: :delete %>
      </div>
    </div>
  <% end %>
</div>

<h3 class="text-center mt-4">Articles</h3>


<div class="flickr_pagination">
  <%= will_paginate @articales, :container => false %>
</div>

<%= render 'articales/article' %>

<div class="flickr_pagination mb-4">
  <%= will_paginate @articales, :container => false %>
</div>